<ol class="owl-theme owl-carousel" data-mage-init='{"carousel":{"baseUrl": "<?= $block->escapeJs($block->getBaseUrl());?>"}}'>
    <li><img src="<?=$this->getViewFileUrl('images/motorolla.png'); ?>" alt=""></li>
    <li><img src="<?=$this->getViewFileUrl('images/alofeng.png'); ?>" alt=""></li>
    <li><img src="<?=$this->getViewFileUrl('images/icom.png'); ?>" alt=""></li>
    <li><img src="<?=$this->getViewFileUrl('images/kenwood.png'); ?>" alt=""></li>
    <li><img src="<?=$this->getViewFileUrl('images/hytera.png'); ?>" alt=""></li>
    <li><img src="<?=$this->getViewFileUrl('images/motorolla.png'); ?>" alt=""></li>
    <li><img src="<?=$this->getViewFileUrl('images/alofeng.png'); ?>" alt=""></li>
    <li><img src="<?=$this->getViewFileUrl('images/icom.png'); ?>" alt=""></li>
    <li><img src="<?=$this->getViewFileUrl('images/kenwood.png'); ?>" alt=""></li>
    <li><img src="<?=$this->getViewFileUrl('images/hytera.png'); ?>" alt=""></li>
</ol>
