<h1 class="home-page-title"><?= __('Bedankt voor uw bestelling bij PortofoonWEB!'); ?></h1>
<div class="content-home-page">
    <div>
        <p class="title"><?=__('Goed om te weten')?></p>
        <p class="description"><?=__('Bent u tevreden over het bestelproces like dan onze Facebook pagina of laat een review achter, zo maakt u ook nog eens kans op een leuke cadeau bon ter waarde van € 100,- Wilt u graag op de hoogte blijven van het laatste nieuws en speciale aanbiedingen meld u zich dan aan op onze nieuwsbrief.')?></p>

        <p class="title"><?=__('Wat gaat er nu gebeuren?')?></p>
        <p class="description"><?=__('Per email heeft u een bevestiging ontvangen van uw bestelling met Ordernummer [ordernummer]. Heeft u de bestelling op een werkdag voor 17:00 gedaan en betaald, dan gaan wij nu direct aan de slag om te zorgen dat u het morgen in huis heeft. Heeft u vragen over de bestelling neem dan contact met ons op 0512 – 745293 of stuur ons een email aan info@portofoonweb.nl.')?></p>

        <p class="title"><?=__('Wist u dat?')?></p>
        <p class="description"><?=__('PortofoonWEB heeft sinds kort een fenomenaal nieuwe techniek genaamd Smart Portofoons. Een portofoon systeem met ongekende mogelijkheden en onbeperkt bereik! Klik op deze link voor meer informatie.')?></p>
    </div>
</div>
<div class="home-page_social-media">
    <div>
        <img src=" <?=$this->getViewFileUrl('images/Smartportofoon_Logo.png'); ?>" width="200"/>
    </div>
    <a href="https://www.facebook.com/"><i class="fab fa-facebook-square"></i></a>
    <a href="https://twitter.com/?lang=uk"><i class="fab fa-twitter-square"></i></a>
</div>
